# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest  #windiws-latest #macos-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '22.x'
  - script: npm ci
    displayName: 'Install playwright Dependencies'

  - script: npx playwright install --with-deps
    displayName: 'install playwright browsers'

  - script: SECRET_KEY=$(SECRET_KEY_VAL) npm run $(SCRIPT_KEY_VAL)
    displayName: 'run tests'