# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest  #windiws-latest #macos-latest

parameters:
  - name: SCRIPT_KEY_VAL2
    displayName: 'Select Script Kay'
    type: string
    default: 'test_stag_ui_cr_hl_api_novisual'
    values:
      - test_stag_ui_cr_hl_api_novisual
      - test_stag
      - test_stag_cr_hl
       
steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '22.x'
  - script: npm ci
    displayName: 'Install playwright Dependencies'

  - script: npx playwright install --with-deps
    displayName: 'install playwright browsers'

  #- script: SECRET_KEY=$(SECRET_KEY_VAL) npm run $(SCRIPT_KEY_VAL)  --this comes from variables 
  - script: SECRET_KEY=$(SECRET_KEY_VAL) npm run $(SCRIPT_KEY_VAL2)  #this comers from above variables set
    displayName: 'run tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    condition: always()

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**test-results/junit-report.xml'
      testRunTitle: 'playwright junit report'
    condition: always()
